# Example vars.yml

# String variables
app_name: "MyApp"
app_version: "1.0.0"

# Integer variables
max_retries: 5
timeout: 30

# Boolean variables
enable_feature_x: true
is_production: false

# List variables (Array of items)
allowed_ips:
  - "192.168.1.1"
  - "192.168.1.2"
  - "192.168.1.3"

# Dictionary variables (Hash of key-value pairs)
database:
  host: "db.example.com"
  port: 5432
  user: "admin"
  password: "password123"

# Complex variables (Nested lists and dictionaries)
servers:
  - name: "web01"
    ip: "192.168.1.10"
    role: "web"
  - name: "db01"
    ip: "192.168.1.20"
    role: "database"

# Variable with Jinja2 template (dynamically generated)
env_path: "/home/{{ ansible_user }}/{{ app_name }}/{{ app_version }}"

# A list with variables that can be dynamically assigned
user_list:
  - user1
  - user2
  - user3

# File path variable
log_path: "/var/log/{{ app_name }}/"