
# variables:
# Local Variable: Defined within a task (using set_fact).
# Global Variable: Defined at the playbook level (using vars).
# Prompt Variable: Defined by asking the user during playbook execution (vars_prompt).
# Vars File: Defined in an external file and included in the playbook (vars_files).
# Command Line Variable: Passed directly via the command line using -e or --extra-vars.

- name: local variables
  hosts: localhost
  gather_facts: true
  vars: # Global variables
    var1: "hello var1"
    home: "/home/ec2-user"
  vars_files:  "{{ home }}/advance-pocs-all/Ansible/variables.yml" # no "-" for vars for more variables

  tasks:
    - name: print local vars
      debug:
        msg: "{{ var1 }}"

    - name: set fact variables 
      set_fact:
        fact_var1: "/home/ec2-user"

# using variables which is declared in vars_file path
    - name: print variables from vars file
      debug:
        msg: "{{ app_name }}/{{ app_version }}"

    - name: prompt the variable runtime
      vars_prompt:
        prompt: "enter the password runtime dynamically:"
    
    # import task
    - include_tasks: "{{ fact_var1 }}/advance-pocs-all/Ansible/hello.yml"  # we have write mutiple others tassk in seperate file and the include in any playbook as requirments
      
# can execute mutiple playbooks in single file
- name: Example of command line variable
  hosts: localhost
  tasks:
    - name: Print command line variable
      debug:
        msg: "{{ cmd_var }}"   # no variables passed from CMD Line below undefined vars error you get

# [ec2-user@ip-172-31-92-178 Ansible]$ ansible-playbook -e cmd_var="command var value" vars.yml   ---- command line passing vars

        
# TASK [Print command line variable] *******************************************************************************************
# fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'cmd_var' is undefined. 'cmd_var' is undefined\n\nThe error appears to be in '/home/ec2-user/advance-pocs-all/Ansible/vars.yml': line 29, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - name: Print command line variable\n      ^ here\n"}


#importing the playbook 

- import_playbook: "{{ linux_path }}/advance-pocs-all/Ansible/gather_facts.yml"
  vars: 
    linux_path: "/home/ec2-user"
  #should be in "" for import playbook as we have path var

